### ISSUE TITLE
PHP SDK improvements

### ISSUE THREAD

**Issue by adri** [amplitude/experiment-php-server#10]
We're evaluating the PHP SDK and found a few issues we see with this package:

* Depends directly on Guzzle, instead use [php-http/discovery](https://github.com/php-http/discovery). This allows people to use their own compatible client.
* Depends on Monolog, instead use a PSR Log. You can [suggest](https://getcomposer.org/doc/04-schema.md#suggest) monolog 
* Run tests run on a (recent) PHP version matrix, not just 7.4 (this version and 8.0 is [unsupported](https://www.php.net/eol.php))
* Use [phpstan](https://phpstan.org)
* 2 days ago `lastguest/murmurhash` was pulled in that's 6 years old, 2 years last commit. The SDK should require minimum deps.

**Comment by bgiori** [comment]
Thanks @adri! Appreciate your expertise here.

**Comment by ruudk** [comment]
With the merge of #13 this can be closed 🎉
