### ISSUE TITLE
Namespaced VERSION constant

### ISSUE THREAD

**Issue by mpazienza-literati** [amplitude/experiment-php-server#15]
Non-blocking, but I am hitting a noisy warning when using this library in conjunction with WordPress that the VERSION constant is already defined, probably due to a conflict with something else in WordPress. Consider Name spacing it to prevent collisions.

`Warning: Constant VERSION already defined in ../../experiment-php-server/src/Version.php on line 2`

**Comment by tyiuhc** [comment]
@mpazienza-literati, many thanks for raising this issue. `VERSION` is now namespaced in v0.5.1
